# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://waldenlan.github.io
date_format: "ordinal"
title: Qi's Blog
subtitle: Back to my own...
description: "Walden Lian's personal blog"
keywords: Qi's Blog, Walden Lian, WaldenLan
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: Walden Lian
organization: ECE@SJTU.
organization_url: http://umji.sjtu.edu.cn/cn/
location: Shanghai, China
email: 446731905@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlight:     true
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: waldenlian/waldenlian.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: waldenlian
segmentfault_username: waldenlan
facebook_username: waldenlan
zhihu_username: WaldenLian

# ---------------- #
#      Comments    #
# ---------------- #
#support provider: disqus
comments_provider: disqus
# !!!Important!!! Please modify usernames below to yours
disqus_username: qi_lian

# 在使用 disqus 的时候可点击显示多说评论框
#lazy_load_duoshuo: false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-105984203-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_prog_keywords: [C, C++, Python, Java, MATLAB, LaTex, Markdown]
skill_web_dev_keywords: [HTML/CSS, JavaScript, jQuery, Django, MySQL, MongoDB]
skill_hardware_OS_keywords: [Bash Scripting, Verilog HDL, MIPS Assembly, MacOS, Linux (Ubuntu), Windows]
